# Generated by Django 3.0.4 on 2020-12-18 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=20)),
                ('payment', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order_time', models.DateField()),
                ('channel', models.CharField(max_length=20)),
                ('packing_cost', models.IntegerField()),
                ('packing_time', models.DateField(blank=True)),
                ('arrive_time', models.DateField(blank=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.Client')),
            ],
        ),
    ]
