# Generated by Django 3.1.4 on 2021-01-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20210103_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('已審核', '已審核'), ('備貨中', '備貨中'), ('已達包裹中心', '已達包裹中心'), ('已達物流中心', '已達物流中心'), ('已出貨', '已出貨'), ('已到達', '已到達'), ('已辦理退貨', '已辦理退貨'), ('退貨審核不通過', '退貨審核不通過')], default=0, max_length=20, verbose_name='response')),
            ],
        ),
    ]
